
name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CONVENIENCE_SCRIPT: sh -c "$(wget -qO- 'https://raw.githubusercontent.com/felipecassiors/dotfiles/${{ github.sha }}/scripts/install_dotfiles.sh')"

jobs:
  clone-and-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./install

  convenience-script:
    runs-on: ubuntu-latest

    steps:
      - run: $CONVENIENCE_SCRIPT

  convenience-script-for-work:
    runs-on: ubuntu-latest

    steps:
      - run: HOSTNAME=inatel $CONVENIENCE_SCRIPT
